/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;

/**
 *
 * @author richy
 */
public class ui extends javax.swing.JFrame {

    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jCheckBox18 = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Customer Response");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("This information wil not be used for unlawful activities.");

        jLabel3.setText("Q1.Are you working?");

        jCheckBox1.setText("Yes");

        jCheckBox2.setText("No");
        buttonGroup1.add(jCheckBox1);
        buttonGroup1.add(jCheckBox2);

        jLabel4.setText("Q2.Where do you work?");

        jButton1.setText("Answer");

        jLabel5.setText("Q3.Are you a student?");

        jCheckBox3.setText("Yes");

        jCheckBox4.setText("No");
        buttonGroup2.add(jCheckBox3);
        buttonGroup2.add(jCheckBox4);

        jLabel6.setText("Q4.Level of study?");

        jButton2.setText("Answer");

        jLabel7.setText("Q5.Current residence?");

        jButton3.setText("Answer");

        jLabel8.setText("Q6.Social media account(s)?");

        jButton4.setText("Answer");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton7.setText("Cancel");

        jButton8.setText("Ok");
        buttonGroup.add(jCheckBox9);
        buttonGroup.add(jCheckBox10);
        buttonGroup.add(jCheckBox11);
        buttonGroup.add(jCheckBox12);
        buttonGroup.add(jCheckBox13);

        jPanel2.setVisible(false);

       jCheckBox1.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {

               if(jCheckBox1.isSelected()){
                   jButton1.setEnabled(true);
               }
           }
       });
       jCheckBox2.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               if(jCheckBox2.isSelected()){
                   jButton1.setEnabled(false);
               }
           }
       });
        jButton8.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                    int result= JOptionPane.showConfirmDialog(jPanel2,"Confirm to Edit");
                    switch (result){
                        case JOptionPane.YES_OPTION :
                            jPanel2.setVisible(false);
                            //code

                            break;
                        case JOptionPane.NO_OPTION:
                            //code
                            jPanel2.setVisible(false);
                            break;
                        case JOptionPane.CANCEL_OPTION:
                            jPanel2.setVisible(false);
                            //code
                            break;
                        case JOptionPane.CLOSED_OPTION:
                            jPanel2.setVisible(false);
                            //code
                            break;
                    }
                }

        });
        displayProductsInAssessment();
        jButton7.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPanel2.setVisible(false);
            }
        });
        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buttonGroup5.add(jCheckBox5);
                buttonGroup5.add(jCheckBox6);
                buttonGroup5.add(jCheckBox7);
                buttonGroup5.add(jCheckBox8);
                buttonGroup5.add(jCheckBox18);
                jPanel2.setVisible(true);
                jLabel9.setText("SELECT ONE BELLOW");
                jLabel32.setText("Teacher");
                jLabel33.setText("Doctor");
                jLabel34.setText("Farmer");
                jLabel35.setText("Business");
                jLabel36.setText("industry");
                jCheckBox5.setVisible(true);
                jCheckBox6.setVisible(true);
                jCheckBox7.setVisible(true);
                jLabel32.setVisible(true);
                jLabel33.setVisible(true);
                jLabel34.setVisible(true);
                jLabel35.setVisible(true);
                jLabel36.setVisible(true);
                if(jCheckBox5.isSelected()){
                    responder[1] =1;
                }
                else if(jCheckBox6.isSelected()){
                    responder[1]=2;
                }
                else if(jCheckBox7.isSelected()){
                    responder[1]=3;
                }
                else if(jCheckBox8.isSelected()){
                    responder[1]=4;
                }
                else if(jCheckBox18.isSelected()){
                    responder[1]=5;
                }



            }
        });
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buttonGroup5.add(jCheckBox5);
                buttonGroup5.add(jCheckBox6);
                buttonGroup5.add(jCheckBox7);
                buttonGroup5.add(jCheckBox8);
                buttonGroup5.add(jCheckBox18);
                jPanel2.setVisible(true);
                jLabel32.setVisible(true);
                jLabel33.setVisible(true);
                jLabel34.setVisible(true);
                jLabel35.setVisible(true);
                jLabel36.setVisible(true);
                jLabel9.setText("SELECT ONE BELLOW");
                jLabel32.setText("Primary");
                jLabel33.setText("Secondary");
                jLabel34.setText("Diploma");
                jLabel35.setText("Degree");
                jLabel36.setText("Postgraduate");
                jCheckBox5.setVisible(true);
                jCheckBox6.setVisible(true);
                jCheckBox7.setVisible(true);

                if(jCheckBox5.isSelected()){
                    responder[3]=1;
                }
                else if(jCheckBox6.isSelected()){
                    responder[3]=2;
                }
                else if(jCheckBox7.isSelected()){
                    responder[3]=3;
                }
                else if(jCheckBox8.isSelected()){
                    responder[3]=4;
                }
                else if(jCheckBox18.isSelected()){
                    responder[3]=5;
                }

            }
        });
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buttonGroup5.add(jCheckBox5);
                buttonGroup5.add(jCheckBox6);
                buttonGroup5.add(jCheckBox7);
                buttonGroup5.add(jCheckBox8);
                buttonGroup5.add(jCheckBox18);
                jPanel2.setVisible(true);
                jLabel9.setText("SELECT ONE BELLOW");
                jCheckBox5.setVisible(false);
                jCheckBox6.setVisible(false);
                jCheckBox7.setVisible(false);
                jLabel32.setVisible(false);
                jLabel33.setVisible(false);
                jLabel34.setVisible(false);
                jLabel35.setVisible(true);
                jLabel36.setVisible(true);
                jLabel32.setVisible(false);
                jLabel33.setVisible(false);
                jLabel34.setVisible(false);
                jLabel35.setText("Kenya");
                jLabel36.setText("Other");

                if(jCheckBox8.isSelected()){
                    responder[4]=1;
                }
                else if(jCheckBox18.isSelected()){
                    responder[4]=0;
                }

            }
        });
        jButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buttonGroup5.remove(jCheckBox5);
                buttonGroup5.remove(jCheckBox6);
                buttonGroup5.remove(jCheckBox7);
                buttonGroup5.remove(jCheckBox8);
                buttonGroup5.remove(jCheckBox18);
                jPanel2.setVisible(true);
                jLabel9.setText("SELECT ONE BELLOW");
                jCheckBox5.setVisible(true);
                jCheckBox6.setVisible(true);
                jCheckBox7.setVisible(true);
                jLabel32.setVisible(true);
                jLabel33.setVisible(true);
                jLabel34.setVisible(true);
                jLabel35.setVisible(true);
                jLabel36.setVisible(true);
                jLabel32.setText("Whatsapp");
                jLabel33.setText("Instagram");
                jLabel34.setText("Tweeter");
                jLabel35.setText("Facebook");
                jLabel36.setText("TikTok");
                int[] account=new int[5];
                if(jCheckBox5.isSelected()){
                    responder[5]=1;
                }else {
                    responder[5]=0;
                }
                if(jCheckBox6.isSelected()){
                    responder[6]=2;
                }else {
                    responder[6]=0;
                }
                if(jCheckBox7.isSelected()){
                    account[2]=3;
                }else {
                    account[2]=0;
                }
                if(jCheckBox8.isSelected()){
                    account[3]=4;
                }else {
                    account[3]=0;
                }
                if(jCheckBox18.isSelected()){
                    account[4]=5;
                }else {
                    account[4]=0;
                }
                int[] data=socialmedia();
                for (int i=0;i<data.length;i++){
                    responder[i+5]=data[i];
                }

            }
        });

        jButton6.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if((jCheckBox14.isSelected()||jCheckBox15.isSelected())&&(jCheckBox16.isSelected()||jCheckBox17.isSelected())){
                    if(jCheckBox1.isSelected()){
                        responder[0]=1;
                    }
                    else if(jCheckBox2.isSelected()){
                        responder[1]=0;
                        responder[0]=0;
                    }
                    if(jCheckBox3.isSelected()){
                        responder[2]=1;
                    }
                    else if(jCheckBox4.isSelected()){
                        responder[2]=0;
                    }
                    if(jCheckBox14.isSelected()){
                        responder[10]=1;
                    }
                    else if(jCheckBox15.isSelected()){
                        responder[10]=0;
                    }
                    if(jCheckBox16.isSelected()){
                        responder[11]=1;
                    }
                    else if(jCheckBox17.isSelected()){
                        responder[11]=0;
                    }
                    boolean check=false;
                    if(responder[0]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Question 1");
                    }else {
                        check=true;
                    }
                    if(responder[1]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Question two");
                    }else {
                        check=true;
                    }
                    if(responder[3]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Question three");
                    }else {
                        check=true;
                    }
                    if(responder[4]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Question four");
                    }else {
                        check=true;
                    }
                    if(responder[5]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Question five");
                    }else {
                        check=true;
                    }
                    if(responder[5]!=null||responder[6]!=null||responder[7]!=null||responder[8]!=null||responder[9]!=null){
                        check=true;
                    }else {
                        JOptionPane.showMessageDialog(jPanel1,"Please select one option in Q6");

                    }
                    if(responder[10]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Q7");
                    }else {
                        check=true;
                    }
                    if(responder[11]==null){
                        JOptionPane.showMessageDialog(jPanel1,"Answer Qn 8");
                    }else {
                        check=true;
                    }
                    if(check){
                        if (databaseControl.responder(responder[0],responder[1],responder[2],responder[3],responder[4],responder[5],responder[6],responder[7],responder[8],responder[9],responder[10],responder[11],responder[12])){
                            JOptionPane.showMessageDialog(jPanel1,"Data is received proceed to assess next product");
                        }
                        else {
                            JOptionPane.showMessageDialog(jPanel3,"Error Occurred try again later");
                        }
                    }


                }
                else {
                    JOptionPane.showMessageDialog(jPanel3,"You have to answer Q7 and Q8");

                }
            }
        });
        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(jCheckBox9.isSelected()){
                    String name = jLabel25.getText();
                    String[] info= databaseControl.product_in_assessment(products().get(name));
                    jLabel12.setText(info[0]);
                    jLabel14.setText(info[1]);
                    jLabel16.setText(info[2]);
                    jLabel18.setText(info[3]);
                    jLabel20.setText(info[4]);
                    int id=0;
                    try {
                        id = Integer.parseInt(products().get(name));
                        if(id==Integer.parseInt(products().get(name))){
                            responder[12]=id;
                        }
                    }catch (NumberFormatException sizeException){
                        JOptionPane.showMessageDialog(jPanel1, "Invalid");
                    }

                } else if (jCheckBox10.isSelected()) {
                    String name = jLabel26.getText();
                    String[] info= databaseControl.product_in_assessment(products().get(name));
                    jLabel12.setText(info[0]);
                    jLabel14.setText(info[1]);
                    jLabel16.setText(info[2]);
                    jLabel18.setText(info[3]);
                    responder[12]= Integer.valueOf(info[5]);
                    jLabel20.setText(info[4]);

                } else if (jCheckBox11.isSelected()) {
                    String name = jLabel27.getText();
                    String[] info= databaseControl.product_in_assessment(products().get(name));
                    jLabel12.setText(info[0]);
                    jLabel14.setText(info[1]);
                    jLabel16.setText(info[2]);
                    jLabel18.setText(info[3]);
                    jLabel20.setText(info[4]);
                    responder[12]= Integer.valueOf(info[5]);

                } else if (jCheckBox12.isSelected()) {
                    String name = jLabel28.getText();
                    String[] info= databaseControl.product_in_assessment(products().get(name));
                    jLabel12.setText(info[0]);
                    jLabel14.setText(info[1]);
                    jLabel16.setText(info[2]);
                    jLabel18.setText(info[3]);
                    jLabel20.setText(info[4]);
                    responder[12]= Integer.valueOf(info[5]);

                }else if(jCheckBox13.isSelected()){
                    String name = jLabel29.getText();
                    String[] info= databaseControl.product_in_assessment(products().get(name));
                    jLabel12.setText(info[0]);
                    jLabel14.setText(info[1]);
                    jLabel16.setText(info[2]);
                    jLabel18.setText(info[3]);
                    jLabel20.setText(info[4]);
                    responder[12]= Integer.valueOf(info[5]);

                }
            }
        });
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jCheckBox6)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                                                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                        .addGap(67, 67, 67)
                                                                                                        .addComponent(jCheckBox5))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGap(67, 67, 67)
                                                                                                .addComponent(jCheckBox18))))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jButton7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                                                .addComponent(jButton8)))
                                                .addGap(0, 96, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBox18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton7)
                                        .addComponent(jButton8))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("**Please choose a product in the right side to assess**");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jCheckBox1)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jCheckBox2))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(jButton1))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jCheckBox3)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jCheckBox4)))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButton3)
                                                                        .addComponent(jButton4)
                                                                        .addComponent(jButton2))))
                                                .addGap(102, 102, 102))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCheckBox1)
                                                        .addComponent(jCheckBox2))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCheckBox3)
                                                        .addComponent(jCheckBox4))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton2))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton3))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton4))
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Product Assessment");

        jLabel11.setText("Name");

        jLabel13.setText("Size");

        jLabel15.setText("Weight");

        jLabel17.setText("Price");

        jLabel19.setText("Color");

        jLabel30.setText("Q7.Would you like to purchase the product below?");

        jCheckBox14.setText("Yes");

        jCheckBox15.setText("No");
        buttonGroup3.add(jCheckBox14);
        buttonGroup3.add(jCheckBox15);

        jLabel31.setText("Q8. Are you capable of purchasing it?");

        jCheckBox16.setText("Yes");

        jCheckBox17.setText("No");
        buttonGroup4.add(jCheckBox16);
        buttonGroup4.add(jCheckBox17);

        jButton6.setText("Confirm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jCheckBox14)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBox15))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jCheckBox16)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBox17)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                        .addComponent(jCheckBox14)
                                        .addComponent(jCheckBox15))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCheckBox16)
                                                        .addComponent(jCheckBox17))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel17)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton6)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("PRODUCTS");

        jLabel23.setText("NAME");

        jLabel24.setText("ACTION");

        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jButton5.setText("Assess");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(53, 53, 53))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButton5)
                                                                        .addComponent(jCheckBox10)
                                                                        .addComponent(jCheckBox9)
                                                                        .addComponent(jCheckBox11)
                                                                        .addComponent(jCheckBox12)
                                                                        .addComponent(jCheckBox13))
                                                                .addGap(69, 69, 69))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(104, 104, 104))))
        );

        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox10)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox11)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox12)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration
    databaseControl databaseControl = new databaseControl();
    ButtonGroup buttonGroup = new ButtonGroup();
    ButtonGroup buttonGroup1 = new ButtonGroup();
    ButtonGroup buttonGroup2 = new ButtonGroup();
    ButtonGroup buttonGroup3 = new ButtonGroup();
    ButtonGroup buttonGroup4 = new ButtonGroup();
    ButtonGroup buttonGroup5 = new ButtonGroup();
    productControl productControl = new productControl();


    public HashMap<String,String > products(){
        HashMap<String,String> product = new HashMap<>();
        productControl.Assessmentdisplayproductid();
        productControl.displayAssementNames();

        String[] list;
        String[] ids;
        list=productControl.displayAssementNames();
        ids=productControl.Assessmentdisplayproductid();
        int length= databaseControl.AssessmentNameCount();
            for(int i =0;i<length;i++){
                product.put(list[i],ids[i]);
            }
        return  product;
    }
    Integer[] responder= new Integer[13];
    public int workplace(int workplace ){

        if(jCheckBox5.isSelected()){
            workplace=1;
        }
         if(jCheckBox6.isSelected()){
             workplace=2;
        }
         if(jCheckBox7.isSelected()){
            workplace=3;
        }
        if(jCheckBox8.isSelected()){
             workplace=4;
        }
         if(jCheckBox18.isSelected()){
            workplace=5;
        }
        return workplace;
    }
    public int levelofstudy(){
        int levelofstudy = 0;
        if(jCheckBox5.isSelected()){
            levelofstudy=1;
        }
        else if(jCheckBox6.isSelected()){
            levelofstudy=2;
        }
        else if(jCheckBox7.isSelected()){
            levelofstudy=3;
        }
        else if(jCheckBox8.isSelected()){
            levelofstudy=4;
        }
        else if(jCheckBox18.isSelected()){
            levelofstudy=5;
        }
        return levelofstudy;
    }
    public int[] socialmedia(){
        int[] account=new int[5];
        if(jCheckBox5.isSelected()){
            account[0]=1;
        }else {
         //   account[0]=0;
        }
        if(jCheckBox6.isSelected()){
            account[1]=2;
        }else {
           // account[1]=0;
        }
         if(jCheckBox7.isSelected()){
            account[2]=3;
        }else {
             //account[2]=0;
         }
        if(jCheckBox8.isSelected()){
            account[3]=4;
        }else {
           // account[3]=0;
        }
         if(jCheckBox18.isSelected()){
            account[4]=5;
        }else {
            // account[4]=0;
         }
        return account;
    }
    public int currentResidence(){
        int residence = 0;
         if(jCheckBox8.isSelected()){
            residence=1;
        }
        else if(jCheckBox18.isSelected()){
            residence=0;
        }
        return residence;
    }

    public void displayProductsInAssessment(){

        String[] list;
        list=productControl.displayAssementNames();
        int length= databaseControl.AssessmentNameCount();
        if(length==0){
        }
        else if(length==1){
            jLabel25.setText(list[0]);
        } else if (length==2) {
            jLabel25.setText(list[0]);
            jLabel26.setText(list[1]);

        } else if (length==3) {
            jLabel25.setText(list[0]);
            jLabel26.setText(list[1]);
            jLabel27.setText(list[2]);
        } else if (length==4) {
            jLabel25.setText(list[0]);
            jLabel26.setText(list[1]);
            jLabel27.setText(list[2]);
            jLabel28.setText(list[3]);
        }
        else if (length==5) {
            jLabel25.setText(list[0]);
            jLabel26.setText(list[1]);
            jLabel27.setText(list[2]);
            jLabel28.setText(list[3]);
            jLabel29.setText(list[4]);
        }
        else {
            jLabel25.setText(list[0]);
            jLabel26.setText(list[1]);
            jLabel27.setText(list[2]);
            jLabel28.setText(list[3]);
            jLabel29.setText(list[4]);
        }
    }

}
